CREATE TABLE `radio_stations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`link` varchar(255) NOT NULL,
	`logo` varchar(255) NOT NULL,
	`is_active` boolean NOT NULL DEFAULT true,
	`created_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `radio_stations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `user` (
	`id` int AUTO_INCREMENT NOT NULL,
	`authKey` varchar(255),
	`manager_id` int,
	`name` varchar(255),
	`lname` varchar(255),
	`gender` int,
	`dob` int,
	`passwordHash` varchar(255),
	`passwordResetToken` varchar(255),
	`email` varchar(255),
	`phone` varchar(255),
	`pin` varchar(255),
	`country` varchar(255),
	`status` int,
	`title` varchar(255),
	`role` int,
	`dateBannedUntil` int,
	`avatar` varchar(255),
	`idEMerchant` int,
	`countryCode` varchar(10),
	`idTimezone` int,
	`streetName` varchar(255),
	`streetNumber` varchar(50),
	`postCode` varchar(50),
	`city` varchar(255),
	`optionalAddress` varchar(255),
	`notifications` int,
	`depositLimit` int,
	`cid` varchar(255),
	`idReferral` varchar(255),
	`idMaster` varchar(255),
	`hadReferralDiscount` int,
	`language` varchar(50),
	`timezoneApproved` int,
	`visit_token` varchar(255),
	`migrate` int,
	`trxId` int,
	`idReferralUser` int,
	`fromWhere` int,
	`resetPassword` int,
	`commissionReferral` int,
	`commissionAgent` int,
	`type` int,
	`emailVerified` int,
	`phoneVerified` int,
	`tokenVerify` varchar(255) DEFAULT NULL,
	`created_at` datetime,
	`updated_at` datetime,
	`deleted_at` datetime,
	`password` varchar(255),
	`mlm_level` int DEFAULT 0,
	`idOwner` int,
	`idSuper` int,
	`idSales` int,
	`idAgent` int,
	`idTerminal` int,
	`idReferralHierarchyIds` varchar(255) DEFAULT NULL,
	`commission_shares_percent` int,
	CONSTRAINT `User_id` PRIMARY KEY(`id`)
);
