// src/database/schema/user.ts
import {
    mysqlTable,
    int,
    varchar,
    datetime,
    text,
  } from 'drizzle-orm/mysql-core';
  import { sql } from 'drizzle-orm';
  
  export const users = mysqlTable('user', {
    id: int('id').primaryKey().autoincrement().notNull(),

    authKey: varchar('authKey', { length: 255 }),
    managerId: int('manager_id'),
    email: varchar('email', { length: 255 }).unique(),
    name: varchar('name', { length: 255 }),
    lname: varchar('lname', { length: 255 }),
    gender: int('gender'),
    dob: int('dob'),
    passwordHash: varchar('passwordHash', { length: 255 }),
    passwordResetToken: varchar('passwordResetToken', { length: 255 }),
    phone: varchar('phone', { length: 255 }),
    pin: varchar('pin', { length: 255 }),
    country: varchar('country', { length: 255 }),
    status: int('status'),
    title: varchar('title', { length: 255 }),
    role: int('role'),
    dateBannedUntil: int('dateBannedUntil'),
    avatar: varchar('avatar', { length: 255 }),
    idEMerchant: int('idEMerchant'),
    countryCode: varchar('countryCode', { length: 10 }),
    idTimezone: int('idTimezone'),
    streetName: varchar('streetName', { length: 255 }),
    streetNumber: varchar('streetNumber', { length: 50 }),
    postCode: varchar('postCode', { length: 50 }),
    city: varchar('city', { length: 255 }),
    optionalAddress: varchar('optionalAddress', { length: 255 }),
    notifications: int('notifications'),
    depositLimit: int('depositLimit'),
    cid: varchar('cid', { length: 255 }),
    idReferral: varchar('idReferral', { length: 255 }),
    idMaster: varchar('idMaster', { length: 255 }),
    hadReferralDiscount: int('hadReferralDiscount'),
    language: varchar('language', { length: 50 }),
    timezoneApproved: int('timezoneApproved'),
    visitToken: varchar('visit_token', { length: 255 }),
    migrate: int('migrate'),
    trxId: int('trxId'),
    idReferralUser: int('idReferralUser'),
    fromWhere: int('fromWhere'),
    resetPassword: int('resetPassword'),
    commissionReferral: int('commissionReferral'),
    commissionAgent: int('commissionAgent'),
    type: int('type'),
    emailVerified: int('emailVerified'),
    phoneVerified: int('phoneVerified'),
    tokenVerify: varchar('tokenVerify', { length: 255 }).default(sql`NULL`),
    createdAt: datetime('created_at'),
    updatedAt: datetime('updated_at'),
    deletedAt: datetime('deleted_at'),
    // password: varchar('password', { length: 255 }),
    mlmLevel: int('mlm_level').default(0),
    idOwner: int('idOwner'),
    idSuper: int('idSuper'),
    idSales: int('idSales'),
    idAgent: int('idAgent'),
    idTerminal: int('idTerminal'),
    idReferralHierarchyIds: varchar('idReferralHierarchyIds', { length: 255 }).default(sql`NULL`),
    commissionSharesPercent: int('commission_shares_percent'),
  });
  